In [1]:
import numpy as np

In [2]:
np.zeros(2, 2);

TypeError: data type not understood

In [3]:
np.zeros(2)

array([ 0.,  0.])

In [4]:
np.zeros(2, 2)

TypeError: data type not understood

In [5]:
clear

In [6]:
np.zeros([2, 2])

array([[ 0.,  0.],
       [ 0.,  0.]])

In [7]:
pCloudy = 0.5

In [25]:
pSGivenCloudy = np.array([[0.1, 0.5], [0.9, 0.5]])

In [11]:
pSGivenCloudy

array([ 0.1,  0.5])

In [26]:
pRGivenCloudy = np.array([[0.8, 0.2], [0.2, 0.8]])

In [60]:
pWG = np.array([[[0.99, 0.90],[0.90, 0.01]], [[0.01, 0.10], [0.10, 0.99]]])

In [65]:
sum = 0
for c in range(2):
    for s in range(2):
        for r in range(2):
            for wg in range(2):
                addend = pCloudy * pSGivenCloudy[s][c] * pRGivenCloudy[r][c] * pWG[wg][s][r]
                print(str(c) + " " + str(s) + " " + str(r) + " " + str(wg))
                print(addend)
                sum += addend

In [62]:
sum

1.0

In [59]:
pWG[0][1]

array([ 0.9 ,  0.01])

In [35]:
range(1)

range(0, 1)

In [36]:
for i in range(1): print(i)

0


In [66]:
range(1, 1)

range(1, 1)

In [67]:
sum = 0
for c in range(2):
    for s in range(2):
        for r in range(2):
            wg = 0
            addend = pCloudy * pSGivenCloudy[s][c] * pRGivenCloudy[r][c] * pWG[wg][s][r]
            print(str(c) + " " + str(s) + " " + str(r) + " " + str(wg))
            print(addend)
            sum += addend

0 0 0 0
0.0396
0 0 1 0
0.009
0 1 0 0
0.324
0 1 1 0
0.0009
1 0 0 0
0.0495
1 0 1 0
0.18
1 1 0 0
0.045
1 1 1 0
0.002


In [68]:
sum

0.65000000000000013